# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: database-master-vol-1
    vol_size: 100
  - vol_name: database-cluster-vol-1
    vol_size: 100
  - vol_name: database-cluster-vol-2
    vol_size: 100


# Security group
security_groups:
  - name: Add_ssh
    description: "Add security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: Add_http (port 80)
    description: "Add security group for HTTP port (80)"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: Add_couchDB port 
    description: "Add couchDB port (5984)"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: Add_couchDB port 
    description: "Add couchDB port (4369)"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: Add_couchDB port 
    description: "Add couchDB port (9100-9200)"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: database master-1
    volumes: database-master-vol-1
    meta:
      group: masterDB
  - name: database slaves-1
    volumes: database-cluster-vol-1
    meta:
      group: slavesDB
  - name: database slaves-2
    volumes: database-cluster-vol-2
    meta:
      group: slavesDB


instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: cloud-ass2
instance_flavor: uom.mse.2c9g

