- hosts: localhost
  vars:
    ansible_python_interpreter: /Users/both/opt/anaconda3/bin/python
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    - role: openstack-volume-snapshot

-host: COMP90024
  var_files:
    - host_vars/docker_var.yaml
  gather_facts: true

  roles:
    - role: wp-common
    - role: wp-volumes
    - role: wp-docker
    - role: wp-wordpress
