#Create instances for Database instances
- hosts: localhost
  vars:
    ansible_python_interpreter: ~/opt/anaconda3/bin/python
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
#Set up Environment for Database instances
- hosts: instances
  vars_files:
    - host_vars/docker_var.yaml
  gather_facts: true

  roles:
    - role: env-setup
    - role: env-common
    - role: env-volumes 
    - role: env-docker 

#Set up a website instance
- hosts: localhost
  vars:
    ansible_python_interpreter: ~/opt/anaconda3/bin/python
  vars_files:
    - host_vars/web.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

#set up environment for a website instance
- hosts: websites
  vars_files:
    - host_vars/docker_website.yaml
  gather_facts: true

  roles:
    - role: env-setup
    - role: env-common
    - role: env-volumes 
    - role: env-docker 
 
