---
#Clone git repo our project
- name: clone git repo
    become: yes
    git:
      repo: https://github.com/comp90024-ass2/COMP90024_2021_ASSIGNMENT2.git
      dest: "{{ react_project_path }}"
      force: yes


#Move .dockerignore file from template to server
- name: move requirements files to server 
  tags: 'buildReact'
  become: yes
  template:
    src: '.dockerignore'
    dest: "{{ web_react_path }}"

#Move Dockerfile file from template to server
- name: move Dockerfile files to server 
  tags: 'buildReact'
  become: yes
  template:
    src: 'Dockerfile'
    dest: "{{ web_react_path }}"


- name: traverse into the react directory.
  become: yes
  shell: cd
  args:
    chdir: "{{ web_react_path }}"

- name: Build web react container 
  script: ./setup-react.sh 
  register: buildReact






