---
# Install dependencies
- name: Install dependencies
  task: always
  apt:
    name: ['apt-transport-https','build-essential','python-pip','ca-certificates','curl','gnupg-agent','software-properties-common','git','python3-dev','python3-pip','python3-setuptools','software-properties-common','unzip','vim']
    state: latest
    update_cache: yes

- name: Update pip
  pip:
    name: ['pip']
    state: latest
